apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mySpec
  annotations:
    github.com/project-slug: varuntalus/mySpec
    backstage.io/techdocs-ref: url:https://github.com/varuntalus/mySpec/blob/main/README.md
spec:
  type: other
  lifecycle: experimental
  owner: guests

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: provisioning-system
  description: A system that handles all provisioning-related services and components.
  labels:
    team: provisioning-team
spec:
  owner: guests
  domain: provisioning

---

apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: provisioning
  description: Domain responsible for all payment-related systems and APIs.
spec:
  owner: guests

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-petstore
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: provisioning
  definition:
    $text: ./petstore.oas.yaml
