apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mySpec
  annotations:
    github.com/project-slug: varuntalus/mySpec
spec:
  type: other
  lifecycle: unknown
  owner: guests


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-service-api
  description: My Service API
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    
