apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mySpec
  annotations:
    github.com/project-slug: varuntalus/mySpec
    backstage.io/techdocs-ref: url:https://github.com/varuntalus/mySpec/blob/main/README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-petstore
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: groups
  system: Provisioning
  definition:
    $text: ./petstore.oas.yaml
