
#apiVersion: backstage.io/v1alpha1
#kind: Domain
#metadata:
#  name: provisioning
#  description: Domain responsible for all payment-related systems and APIs.
#spec:
#  owner: guests

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: provisioning-system
  description: A system that handles all provisioning-related services and components.
  labels:
    team: provisioning-team
spec:
  owner: guests
#  domain: provisioning

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: DRaaS
  description: A system that handles all DR services and components.
  labels:
    team: DRaaS-team
spec:
  owner: guests

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: provisioning
  description: The provisioning business unit
spec:
  type: team
  profile:
    displayName: team-provisioning
    email: provisioning@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: Group
  children: [backstage, other]
  members: [vartal]
---

# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: vartal
# spec:
#   profile:
#     displayName: Varun T
#     email: vartal@example.com
#     picture: https://example.com/staff/jenny-with-party-hat.jpeg
#   memberOf: [team-provisioning]

# ---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: DRaaS
  description: The DR business unit
spec:
  type: team
  profile:
    displayName: team-draas
    email: draas@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: Group
  children: [backstage, other]
  members: [vartal]
---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vartal
spec:
  profile:
    displayName: Varun T
    email: vartal@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [team-provisioning, team-draas]


---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orderManagement
  annotations:
    github.com/project-slug: varuntalus/mySpec
    backstage.io/techdocs-ref: url:https://github.com/varuntalus/mySpec/blob/main/README.md
    backstage.io/kubernetes-id: back
    jenkins.io/job-full-name: testing
spec:
  type: service
  lifecycle: experimental
  owner: provisioning
  system: provisioning-system  
  providesApis:
    - orderAPI
  consumesApis:
    - orderStatusUpdate

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: orderStatusUpdate
  description: To Update The Status of the Order
  tags:
    - store
    - rest
  links:
    - url: https://github.com/varuntalus/mySpec
      title: GitHub Repo
      icon: github
    - url: https://github.com/varuntalus/mySpec/blob/main/addPastry.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: DRaaS
  system: DRaaS
  definition:
    $text: ./addPastry.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: orderAPI
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: provisioning
  system: provisioning-system
  definition:
    $text: ./petstore.oas.yaml
